const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'); const root=path.resolve(__dirname,'..');
const url='file://'+root+'/Design/Interface-preview.html';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.LUMA_CHROME_PATH||chromium.executablePath(),args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 const report={kind:'browser-preview-only',nativeBuildRun:false,viewports:[],checks:[],errors:[]};
 const open=async(width,height)=>{const p=await browser.newPage({viewport:{width,height},deviceScaleFactor:1,timezoneId:'UTC'});p.on('pageerror',e=>report.errors.push(e.message));await p.goto(url);await p.evaluate(()=>document.fonts.ready);await p.waitForFunction(()=>audioReady);return p};
 for(const [w,h] of [[320,568],[375,667],[390,844],[430,932],[1440,1000]]){
  const p=await open(w,h);const m=await p.locator('#screen').evaluate(e=>({height:e.clientHeight,content:e.scrollHeight}));assert(m.content<=m.height+1,JSON.stringify({w,h,...m}));
  assert(!/Экспериментальный режим|Список не ограничен|Открывайте Luma ежедневно/.test(await p.locator('#screen').innerText()));
  const box=await p.locator('.rem-help').boundingBox();assert(box.width>=44&&box.height>=44);
  report.viewports.push({w,h,...m});if(w===390)await p.screenshot({path:root+'/Design/Luma-night.png'});if(w===1440)await p.screenshot({path:root+'/Design/Luma-design.png'});await p.close();
 }
 const p=await open(390,844);await p.locator('.rem-help').click();assert.equal(await p.locator('.rem-help-sheet p').count(),9);await p.locator('.rem-help-sheet p').last().scrollIntoViewIfNeeded();assert(await p.locator('.dialog').evaluate(e=>e.scrollTop>0));await p.locator('.dialog').evaluate(e=>e.scrollTop=0);await p.screenshot({path:root+'/Design/Luma-rem-help.png'});await p.getByRole('button',{name:'Закрыть справку'}).click();assert(await p.locator('.rem-help').evaluate(e=>e===document.activeElement));report.checks.push('Long help readable and scrollable; focus returns; no removed labels on Night');
 for(const time of ['09:00','12:00','07:00']){await p.locator('[data-action=alarm-new]').click();await p.locator('[data-input=alarm-time]').fill(time);await p.locator('[data-action=alarm-save]').click()}
 const order=await p.evaluate(()=>sortedAlarms().map(a=>a.id));assert.deepEqual(await p.locator('.alarm .edit').evaluateAll(es=>es.map(e=>e.dataset.value)),order);
 const edit=p.locator('.alarm .edit').first();await edit.scrollIntoViewIfNeeded();const box=await edit.boundingBox();assert(box.width>200&&box.height>=100);await edit.click({position:{x:box.width-6,y:box.height-7}});assert(await p.locator('[data-input=alarm-time]').isVisible());await p.locator('[data-action=close]').click();report.checks.push('Alarm list follows actual next date; blank corner opens time editor');
 await p.locator('[data-action=tab][data-value=settings]').click();assert(!/Будильник в беззвучном режиме/.test(await p.locator('#screen').innerText()));assert.equal(await p.locator('[data-action=phone-vibration]').count(),0);assert.equal(await p.locator('[data-input=delivery]').count(),0);await p.locator('#screen [data-action=route][data-value=watch]').click();assert.deepEqual(await p.locator('#screen [data-input=gap] option').allTextContents(),['3 секунд','8 секунд','12 секунд']);await p.locator('#screen [data-action=route][data-value=phone]').click();report.checks.push('Single AlarmKit route; removed delivery and vibration controls; Watch intervals 3/8/12');
 await p.locator('#sound-file').setInputFiles(root+'/Resources/luma-tone-8.wav');await p.waitForFunction(()=>voices.length===1);assert.equal(await p.evaluate(()=>voices[0].imported),true);await p.locator('#screen [data-input=voice]').selectOption(await p.evaluate(()=>voices[0].id));await p.reload();await p.waitForFunction(()=>audioReady);assert.equal(await p.evaluate(()=>voices.length),1);assert.equal(await p.evaluate(()=>state.defaultDelivery),'systemAlarm');assert.equal(await p.evaluate(()=>state.signal.voice),await p.evaluate(()=>voices[0].id));report.checks.push('Imported audio and selected sound survive reload; AlarmKit default persists');
 await p.locator('[data-action=tab][data-value=journal]').click();await p.locator('[data-action=dream-new]').click();await p.locator('[data-action=journal-record]').click();await p.waitForFunction(()=>recorder?.state==='recording');assert(await p.locator('[data-action=dream-save]').isDisabled());await p.waitForTimeout(900);await p.locator('[data-action=record-stop]').click();await p.waitForFunction(()=>draft.voices.length===1&&!finishing);await p.screenshot({path:root+'/Design/Luma-voice-diary.png'});const voiceID=await p.evaluate(()=>draft.voices[0].id);await p.locator('[data-action=dream-save]').click();assert.equal(await p.evaluate(()=>state.dreams[0].text),'');await p.reload();await p.waitForFunction(()=>audioReady);assert(await p.evaluate(id=>assets.has(id),voiceID));await p.locator('[data-action=tab][data-value=journal]').click();await p.locator('[data-action=dream-edit]').click();await p.locator('[data-action=asset-play]').click();await p.waitForFunction(()=>assetID!==null);await p.locator('[data-action=asset-play]').click();report.checks.push('Voice-only dream saved to IndexedDB, restored after reload and played; saving blocked while recording');
 await p.locator('[data-action=journal-record]').click();await p.waitForFunction(()=>recorder?.state==='recording');await p.waitForTimeout(500);await p.locator('[data-action=record-stop]').click();await p.waitForFunction(()=>draft.voices.length===2&&!finishing);const discarded=await p.evaluate(()=>draft.voices[1].id);await p.locator('[data-action=close]').click();await p.waitForFunction(id=>!assets.has(id),discarded);assert(await p.evaluate(id=>assets.has(id),voiceID));report.checks.push('Cancel removes new recording while keeping previously saved audio');
 await p.locator('[data-action=tab][data-value=night]').click();await p.locator('[data-action=start]').click();await p.locator('[data-action=end]').click();await p.locator('[data-action=tab][data-value=journal]').click();await p.locator('[data-action=feedback]').click();await p.locator('[data-action=journal-record]').click();await p.waitForFunction(()=>recorder?.state==='recording');await p.waitForTimeout(500);await p.locator('[data-action=record-stop]').click();await p.waitForFunction(()=>draft.voices.length===1&&!finishing);await p.locator('[data-action=feedback-save]').click();assert.equal(await p.evaluate(()=>state.sessions[0].feedback.voices.length),1);report.checks.push('Optional session feedback accepts a voice attachment');
 await p.locator('[data-action=dream-edit]').click();await p.locator('[data-action=dream-delete]').click();await p.waitForFunction(id=>!assets.has(id),voiceID);report.checks.push('Deleting a dream removes its stored audio');
 await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.watch').count(),1);
 assert.deepEqual(report.errors,[]);fs.writeFileSync(root+'/Docs/audio-preview-checks.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
